services:
  yourls:
    image: yourls
    restart: always
    ports:
      - 8080:80
    depends_on:
      - mysql
    environment:
      YOURLS_SITE: http://localhost:8080/
      YOURLS_USER: example_username
      YOURLS_PASS: example_password
      YOURLS_DEBUG: "true"
      YOURLS_DB_DRIVER: maria
      YOURLS_DB_NAME: yourls
      YOURLS_DB_USER: root
      YOURLS_DB_PASS: example
      YOURLS_DB_HOST: mysql
    volumes:
      - .:/var/www/html/user/plugins/auditlogdb

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: yourls

